name: Lint Userstyles

on:
  workflow_dispatch:
  pull_request:
    paths-ignore: ["docs/**"]
  push:
    branches: [main]
    paths-ignore: ["docs/**"]

jobs:
  lint:
    if: github.repository == 'catppuccin/userstyles'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.3.5
          cache: true

      - name: Lint
        run: deno task lint
